# Generated by Django 2.2.1 on 2019-05-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('kratica', models.TextField(primary_key=True, serialize=False)),
                ('ime', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OlimpijskeIgre',
            fields=[
                ('leto', models.IntegerField(primary_key=True, serialize=False)),
                ('mesto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tekmovalec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ime', models.TextField()),
                ('rojstvo', models.DateField(null=True)),
                ('mesto', models.IntegerField(null=True)),
                ('rezultat', models.IntegerField(null=True)),
                ('drzava', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_games.Drzava')),
                ('olimpijske_igre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_games.OlimpijskeIgre')),
            ],
        ),
    ]
