# Generated by Django 2.2.1 on 2019-05-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0002_auto_20190514_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ime',
            field=models.TextField(unique=True),
        ),
    ]
