# Generated by Django 2.2.1 on 2019-05-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0004_auto_20190518_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezultat',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ime', to='olympic_games.Disciplina'),
        ),
    ]
