# Generated by Django 2.0.9 on 2019-05-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0004_auto_20190518_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezultat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesto', models.IntegerField(null=True)),
                ('rezultat', models.IntegerField(null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_games.Disciplina')),
                ('ime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_games.Tekmovalec')),
                ('olimpijske_igre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympic_games.OlimpijskeIgre')),
            ],
        ),
    ]
