# Generated by Django 2.0.9 on 2019-05-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0005_rezultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tekmovalec',
            name='drzava',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olympic_games.Drzava'),
        ),
    ]
