# Generated by Django 2.0.9 on 2019-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0006_auto_20190520_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezultat',
            name='rezultat',
            field=models.TextField(null=True),
        ),
    ]
