# Generated by Django 2.0.9 on 2019-05-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0009_auto_20190525_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drzava',
            name='ime',
            field=models.TextField(),
        ),
    ]
