# Generated by Django 2.0.9 on 2019-05-24 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0010_auto_20190525_0116'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tekmovalec',
            unique_together={('ime', 'rojstvo', 'drzava')},
        ),
    ]
