# Generated by Django 2.0.9 on 2019-05-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0011_auto_20190525_0127'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezultat',
            unique_together={('olimpijske_igre', 'disciplina', 'ime', 'mesto')},
        ),
        migrations.AlterUniqueTogether(
            name='tekmovalec',
            unique_together={('drzava', 'ime', 'rojstvo')},
        ),
    ]
