# Generated by Django 2.2.1 on 2019-05-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic_games', '0012_auto_20190525_0141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rezultat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tekmovalec',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='rezultat',
            constraint=models.UniqueConstraint(fields=('olimpijske_igre', 'disciplina', 'ime', 'mesto'), name='rezultat'),
        ),
        migrations.AddConstraint(
            model_name='tekmovalec',
            constraint=models.UniqueConstraint(fields=('drzava', 'ime', 'rojstvo'), name='tekmovalec'),
        ),
    ]
